### ISSUE TITLE
[BUG][V4] Error 500 when using Traefik Reverse Proxy & HTTPS

### ISSUE THREAD

**Issue by Uzurka** [discord-tickets/bot#379]
**Describe the bug**
Settings web panel
Every action on it reports an error 500. If we refresh the page on this error, the content loads fine

**To reproduce**
Set up the v4 of the bot with Docker and use Traefik as a reverse proxy
Docker compose : 

```yaml
version: "3.8"

services:
  ticket-test-mysql:
    image: mysql:8
    hostname: ticket-test-mysql
    volumes: 
      - ticket-test-mysql:/var/lib/mysql
    networks:
      - ticket-test
    environment:
      - MYSQL_ROOT_PASSWORD=ticket
      - MYSQL_DATABASE=discord-ticket
    restart: unless-stopped
  
  ticket-bot:
    image: tickets-bot:v4
    tty: true
    stdin_open: true
    hostname: ticket-test
    volumes:
      - ticket-test:/opt/bot
    networks:
      - ticket-test
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.ticket.entrypoints=web,websecure"
      - "traefik.http.routers.ticket.rule=Host(`ticket.domain.tld)"
      - "traefik.http.services.ticket.loadbalancer.server.port=80"
      - "traefik.http.routers.ticket.tls=true"
      - "traefik.http.routers.ticket.tls.certresolver=letsencrypt"

    depends_on:
      - ticket-test-mysql
    environment:
      - DISCORD_TOKEN=
      - DB_PROVIDER=mysql
      - DB_CONNECTION_URL=
      - HTTP_EXTERNAL=http://ticket.domain.tld
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=80
      - SETTINGS_PORT=81
      - SETTINGS_HOST=0.0.0.0
      - SUPER=
      - PUBLIC_BOT=false
      - HTTP_TRUST_PROXY=true
      - OVERRIDE_ARCHIVE=false
      - DISCORD_SECRET=

    restart: unless-stopped

networks:
  ticket-test:
  traefik_network:
    external: true

volumes:
  ticket-test-mysql:
  ticket-test:
```

**Expected behaviour**
Working settings panel on https://ticket.domain.tld

**Screenshots**
![image](https://user-images.githubusercontent.com/101745008/216553986-57315f25-e177-4b0d-a834-1e49f8c2185c.png)

**Additional context**
