### ISSUE TITLE
[BUG] Error: EACCES: permission denied, copyfile '/app/src/user/banned-guilds.txt' -> 'user/banned-guilds.txt'

### ISSUE THREAD

**Issue by habema** [discord-tickets/bot#588]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I run into this error when trying to run `docker-compose up` the bot using the docker-compose.yml from the instructions in the documentation.

Console:
```
docker-compose up --build
WARN[0000] /Users/redacted/redacted/tickets-bot/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
[+] Running 1/1
 ✔ mysql Pulled                                                                             1.7s
[+] Running 2/0
 ✔ Container tickets-bot-mysql-1  Created                                                   0.0s
 ✔ Container tickets-bot-bot-1    Created                                                   0.0s
Attaching to bot-1, mysql-1
mysql-1  | 2025-02-16 10:23:18+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.4.4-1.el9 started.
bot-1    | Checking environment...
mysql-1  | 2025-02-16 10:23:18+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql-1  | 2025-02-16 10:23:18+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.4.4-1.el9 started.
bot-1    | [preinstall] nothing to do
bot-1    | Preparing the database...
bot-1    | [postinstall] provider=mysql
bot-1    | [postinstall] copying mysql schema & migrations
bot-1    | [postinstall] > npx prisma generate
mysql-1  | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
mysql-1  | 2025-02-16T10:23:18.929514Z 0 [System] [MY-015015] [Server] MySQL Server - start.
mysql-1  | 2025-02-16T10:23:19.135243Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.4.4) starting as process 1
mysql-1  | 2025-02-16T10:23:19.145463Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
mysql-1  | 2025-02-16T10:23:19.301382Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
mysql-1  | 2025-02-16T10:23:19.471759Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
mysql-1  | 2025-02-16T10:23:19.471781Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
mysql-1  | 2025-02-16T10:23:19.474216Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
mysql-1  | 2025-02-16T10:23:19.500908Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.4.4'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
mysql-1  | 2025-02-16T10:23:19.500972Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
bot-1    | Prisma schema loaded from prisma/schema.prisma
bot-1    |
bot-1    | ✔ Generated Prisma Client (v5.22.0) to ./node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client in 111ms
bot-1    |
bot-1    | Start by importing your Prisma Client (See: https://pris.ly/d/importing-client)
bot-1    |
bot-1    | Tip: Need your database queries to be 1000x faster? Accelerate offers you that and more: https://pris.ly/tip-2-accelerate
bot-1    |
bot-1    |
bot-1    | [postinstall] > npx prisma migrate deploy
bot-1    | Prisma schema loaded from prisma/schema.prisma
bot-1    | Datasource "db": MySQL database "tickets" at "mysql"
bot-1    |
bot-1    | 1 migration found in prisma/migrations
bot-1    |
bot-1    |
bot-1    | No pending migrations to apply.
bot-1    |
bot-1    | Starting...
bot-1    | ########  ####  ######   ######   #######  ########  ########
bot-1    | ##     ##  ##  ##    ## ##    ## ##     ## ##     ## ##     ##
bot-1    | ##     ##  ##  ##       ##       ##     ## ##     ## ##     ##
bot-1    | ##     ##  ##   ######  ##       ##     ## ########  ##     ##
bot-1    | ##     ##  ##        ## ##       ##     ## ##   ##   ##     ##
bot-1    | ##     ##  ##  ##    ## ##    ## ##     ## ##    ##  ##     ##
bot-1    | ########  ####  ######   ######   #######  ##     ## ########
bot-1    |
bot-1    | ######## ####  ######  ##    ## ######## ########  ######
bot-1    |    ##     ##  ##    ## ##   ##  ##          ##    ##    ##
bot-1    |    ##     ##  ##       ##  ##   ##          ##    ##
bot-1    |    ##     ##  ##       #####    ######      ##     ######
bot-1    |    ##     ##  ##       ##  ##   ##          ##          ##
bot-1    |    ##     ##  ##    ## ##   ##  ##          ##    ##    ##
bot-1    |    ##    ####  ######  ##    ## ########    ##     ######
bot-1    |
bot-1    | Discord Tickets (​https://discordtickets.app​) bot v4.0.32 by eartharoid
bot-1    | Sponsor this project at https://discordtickets.app/sponsor
bot-1    |
bot-1    |
bot-1    | Warning: The current working directory is not the same as the base directory.
bot-1    |   Base directory:    /app
bot-1    |   Current directory: /home/container
bot-1    |   Learn more at https://lnk.earth/dt-cwd.
bot-1    |  2025-02-16 10:23:20  [NOTICE] Discord Tickets v4.0.32 on Node.js v22.14.0 (linux)
bot-1    |  2025-02-16 10:23:20  [WARN] Uncaught exception
bot-1    |  2025-02-16 10:23:20  [ERROR] Error: EACCES: permission denied, copyfile '/app/src/user/banned-guilds.txt' -> 'user/banned-guilds.txt'
bot-1    |     at copyFileSync (node:fs:3086:11)
bot-1    |     at copyFile (node:internal/fs/cp/cp-sync:104:3)
bot-1    |     at onFile (node:internal/fs/cp/cp-sync:83:25)
bot-1    |     at getStats (node:internal/fs/cp/cp-sync:72:12)
bot-1    |     at copyDir (node:internal/fs/cp/cp-sync:170:9)
bot-1    |     at onDir (node:internal/fs/cp/cp-sync:140:10)
bot-1    |     at getStats (node:internal/fs/cp/cp-sync:68:12)
bot-1    |     at cpSyncFn (node:internal/fs/cp/cp-sync:58:10)
bot-1    |     at Object.cpSync (node:fs:3128:3)
bot-1    |     at Object.<anonymous> (/app/src/index.js:88:4) {
bot-1    |   errno: -13,
bot-1    |   code: 'EACCES',
bot-1    |   syscall: 'copyfile',
bot-1    |   path: '/app/src/user/banned-guilds.txt',
bot-1    |   dest: 'user/banned-guilds.txt'
bot-1    | }
bot-1 exited with code 0
```

My docker-compose.yml:
```yaml
version: "3.9"

services:
  mysql:
    image: mysql:8 --
    restart: unless-stopped
    hostname: mysql
    networks:
      - discord-tickets
    volumes:
      - tickets-mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: tickets
      MYSQL_PASSWORD: insecure # change this to a secure password
      MYSQL_ROOT_PASSWORD: insecure # change this to a (different) secure password
      MYSQL_USER: tickets

  bot:
    image: eartharoid/discord-tickets:4.0
    depends_on:
      - mysql
    restart: unless-stopped
    hostname: bot
    networks:
      - discord-tickets
    ports:
      - 8169:8169
    volumes:
      - tickets-bot:/home/container/user
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    tty: true
    stdin_open: true
    # Please refer to the documentation:
    # https://discordtickets.app/self-hosting/configuration/#environment-variables
    environment:
      DB_CONNECTION_URL: mysql://tickets:insecure@mysql/tickets # change `insecure` to the MYSQL_PASSWORD you set above
      DISCORD_SECRET: ABCD.... # required
      DISCORD_TOKEN: ABCD... # required
      ENCRYPTION_KEY: ABCD.... # required
      DB_PROVIDER: mysql
      HTTP_EXTERNAL: http://127.0.0.1:8169 # change this to your server's external IP (or domain)
      HTTP_HOST: 0.0.0.0
      HTTP_INTERNAL:
      HTTP_PORT: 8169
      HTTP_TRUST_PROXY: "false" # set to true if you're using a reverse proxy
      INVALIDATE_TOKENS:
      OVERRIDE_ARCHIVE: null
      PUBLIC_BOT: "false"
      PUBLISH_COMMANDS: "false"
      SUPER: 319467558166069248,123456789012345678 # my Discord ID

networks:
  discord-tickets:

volumes:
  tickets-mysql:
  tickets-bot:
```

### Steps To Reproduce

1. Follow the exact steps for self-hosting using docker [in the documentation](https://discordtickets.app/self-hosting/installation/docker/).

### Environment

```markdown
- OS: MacOS Sequoia 15.3
```
